# Generated by Django 4.1.4 on 2023-01-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_catagory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
