# Generated by Django 4.1.4 on 2023-01-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_categor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categor',
            new_name='category',
        ),
    ]
